### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by juanicotolengo** [harryhaaren/openAV-Sorcer#8] opened 2015-01-08 16:41 UTC
Here's my output:

[ 33%] Building CXX object CMakeFiles/sorcer.dir/gui/sorcer_ui.cxx.o
/home/juanicotolengo/Programas/openAV-Sorcer/gui/sorcer_ui.cxx: In function ‘const void* extension_data(const char*)’:
/home/juanicotolengo/Programas/openAV-Sorcer/gui/sorcer_ui.cxx:250:16: error: ‘LV2UI_Show_Interface’ does not name a $
/home/juanicotolengo/Programas/openAV-Sorcer/gui/sorcer_ui.cxx:251:16: error: ‘LV2UI_Idle_Interface’ does not name a $
/home/juanicotolengo/Programas/openAV-Sorcer/gui/sorcer_ui.cxx:253:20: error: ‘LV2_UI__showInterface’ was not declare$
/home/juanicotolengo/Programas/openAV-Sorcer/gui/sorcer_ui.cxx:255:20: error: ‘show’ was not declared in this scope
/home/juanicotolengo/Programas/openAV-Sorcer/gui/sorcer_ui.cxx:257:25: error: ‘LV2_UI__idleInterface’ was not declare$
/home/juanicotolengo/Programas/openAV-Sorcer/gui/sorcer_ui.cxx:259:20: error: ‘idle_iface’ was not declared in this s$
/home/juanicotolengo/Programas/openAV-Sorcer/gui/sorcer_ui.cxx: At global scope:
/home/juanicotolengo/Programas/openAV-Sorcer/gui/sorcer_ui.cxx:221:12: warning: ‘int ui_show(LV2UI_Handle)’ defined b$
/home/juanicotolengo/Programas/openAV-Sorcer/gui/sorcer_ui.cxx:229:12: warning: ‘int ui_hide(LV2UI_Handle)’ defined b$
/home/juanicotolengo/Programas/openAV-Sorcer/gui/sorcer_ui.cxx:238:1: warning: ‘int idle(LV2UI_Handle)’ defined but n$
make[2]: *** [CMakeFiles/sorcer.dir/gui/sorcer_ui.cxx.o] Error 1
make[1]: *** [CMakeFiles/sorcer.dir/all] Error 2
make: *** [all] Error 2

**Comment by harryhaaren** [comment] 2015-01-08 16:52
Hi @juanicotolengo.

You will need to update LV2 to build Sorcer: it requires the LV2 Show_Interface extension.

Closing, duplicate of #3 and #4, Cheers, -Harry

**Closed by harryhaaren** 2015-01-08 16:52 UTC
